// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz_FB5Vz9sx6Z8G4s5zNXMYtcVJr-a8dE',
    appId: '1:150133094145:web:b339bf3de67bd30f61cd00',
    messagingSenderId: '150133094145',
    projectId: 'udemyflutterchat-55205',
    authDomain: 'udemyflutterchat-55205.firebaseapp.com',
    storageBucket: 'udemyflutterchat-55205.appspot.com',
    measurementId: 'G-HCHJRNVD15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Nu2FZiCDUisOB7A2a8ARBM-vealuBEU',
    appId: '1:150133094145:android:e4112c36765d6a5f61cd00',
    messagingSenderId: '150133094145',
    projectId: 'udemyflutterchat-55205',
    storageBucket: 'udemyflutterchat-55205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcE2GJ6qpeN0E4DEi9gxWEjjZvHwjEgyE',
    appId: '1:150133094145:ios:c7607a61fc82d8d361cd00',
    messagingSenderId: '150133094145',
    projectId: 'udemyflutterchat-55205',
    storageBucket: 'udemyflutterchat-55205.appspot.com',
    iosClientId: '150133094145-90rcsdcuctu7pa88f53c4cut1aqujhfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
